### ISSUE TITLE
Problem matcher doesn't detect file if compiling without opam

### ISSUE THREAD

**Issue by tchajed** [coq-community/docker-coq-action#17]
With opam, an error looks like this:
```
  - File "./src/demo.v", line 23, characters 0-13:
```

While without, it looks like this:

```
  File "./src/demo.v", line 5, characters 7-13:
```

Could the regex make the leading hyphen optional so that it matches even when running CI without opam?

**Comment by erikmd** [comment]
Hi @tchajed, thanks for opening this. Do you have a public project example that reproduces the issue?
As in the current version of the problem matcher, there is a `?` suffix combinator that should take care of the situation you describe?

`^(?:-\\s+)?File`…

**Comment by tchajed** [comment]
That `?` alone doesn't work because the regex is anchored at the beginning of the line, so without that group there's nothing to match the initial whitespace Coq emits. See https://regex101.com/r/LcySsy/1.

**Comment by tchajed** [comment]
I just made my demo project public, see https://github.com/tchajed/coq-github-ci-test/actions/runs/117090071 for a failure example.

**Comment by erikmd** [comment]
Hi @tchajed, thanks for the link and the project example.
Actually I believe is no "initial whitespace" is added by Coq at the beginning of the line, as the space that we get in the log is just related to the grouping feature IINM.
And the matching succeeded, cf. the following two screenshots:

[![2020-05-27_21-26-31_Screenshot_matching_ok](https://user-images.githubusercontent.com/10367254/83063828-071f8700-a061-11ea-9804-a4731b7d9b6d.png)](https://github.com/tchajed/coq-github-ci-test/runs/714007898?check_suite_focus=true#step:4:417)

[![2020-05-27_21-28-10_Screenshot_matching_OK](https://user-images.githubusercontent.com/10367254/83063856-10105880-a061-11ea-82a9-ecb3f099123c.png)](https://github.com/tchajed/coq-github-ci-test/actions/runs/117090071)

However it seems the filename is not properly recognized (`.github` in the above screenshot instead of ./src/demo.v). This is a different issue actually, but we'll need to investigate this.

**Comment by tchajed** [comment]
I enabled debug logging and this turns out not to be the issue (the whitespace is probably introduced by the logging). It has something to do with my self-hosted runner setup which is causing it to not recognize the workspace root.

**Comment by erikmd** [comment]
@tchajed OK thanks for your reply! but feel free to reopen the issue if need be.
