### ISSUE TITLE
`v1` tag or branch?

### ISSUE THREAD

**Issue by liyishuai** [coq-community/docker-coq-action#69]
To avoid rebuilding `v1` for each user run, we might want to make it a moving tag: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management

**Comment by Zimmi48** [comment]
Oh, I didn't know that the choice to use a branch rather than a tag would have an impact on the way GitHub workflows handle this. When we initially decided to use a branch rather than a tag with @erikmd, this was because we considered the practice of moving tag weird, and not in line with standard best practices about tags.

**Comment by Zimmi48** [comment]
The documentation you linked to doesn't mention this difference. Where did you learn about it?

**Comment by erikmd** [comment]
Indeed, it would be good to have some documentation of this "caching feature", if any
(and if it is really available for both Dockerfile and Typescript actions).

FTR, the choice we had made with @Zimmi48 on this topic is documented here:
https://github.com/coq-community/docker-coq-action#versioning

**Comment by liyishuai** [comment]
I must have misread my build logs. The actions’ Docker images are rebuilt regardless of being a branch or tag. Sorry for the confusion!

**Comment by erikmd** [comment]
OK thanks!

Anyway, I'm pretty sure that the building time at stake (docker build) is negligible.
